---
- name: Create bastion host
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Include bastion vars
      include_vars: bastion-vars

    - name: Include out vars
      include_vars: out_IDs

    - name: Include out vars
      include_vars: vpc-setup


    - name: Create a security group for bastion host
      amazon.aws.ec2_security_group:
        name: sg_bastion
        description: Security group with rule descriptions
        vpc_id: vpc-094f35600a633a170
        region: "{{ region }}"
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 22
      register: sg_bastion

    - name: Creating Bastion Host
      ec2:
        key_name: vprofile-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{ bastion_ami }}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "Bastion_host"
          Project: test-project
          Owner: DevOps Team
        exact_count: 1
        count_tag:
          Name: "Bastion_host"
          Project: test-project
          Owner: DevOps Team
        group_id: "{{sg_bastion.group_id}}"
        vpc_subnet_id: subnet-0500aa02ae788a103
      register: bastionHost_out  