---
- name: Create bastion host
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Include bastion vars
      include_vars: bastion-vars

    - name: Include out vars
      include_vars: out_IDs

    - name: Include out vars
      include_vars: vpc-setup


    - name: Create a security group for bastion host
      amazon.aws.ec2_security_group:
        name: sg_bastion
        description: Security group with rule descriptions
        vpc_id: vpc-094f35600a633a170
        region: "{{ region }}"
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 22
      register: sg_bastion

    - name: Create Bastion Host
      amazon.aws.ec2_instance:
       key_name: karim.pem
       region: "{{ region }}"
       instance_type: t2.micro
       image_id: "{{ bastion_ami }}"
       wait: yes
       wait_timeout: 300
       tags: 
        Name: "Bastion_host"
        Project: test-project
        Owner: DevOps Team
       exact_count: 1
       security_group: "{{ sg_bastion.group_id }}"
       vpc_subnet_id: vpc-094f35600a633a170
      register: bastionHost_out
 