---
- name: create bastion host
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Include bastion vars
      include_vars: bastion-vars

    - name: Include out vars
      include_vars: out_IDs

    - name: create a security group for bastion host
      amazon.aws.ec2_security_group:
        name: "{{ name }}"
        description: sg with rule descriptions
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            ports:
             - 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 22
      register: sg_bastion     

    - name: Launch bastion host instance
      amazon.aws.ec2_instance:
        name: bastion_host
        key_name: karim.pem
        instance_type: t2.micro
        image_id: "{{ bastion_ami }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ public_subnet1.subnet.id }}"
        security_group: "{{ bastion_sg.group_id }}"
        assign_public_ip: yes
      register: bastion_instance  

