---
- name: Create bastion host
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Include bastion vars
      include_vars: bastion-vars

    - name: Include out vars
      include_vars: out_IDs

    - name: Include out vars
      include_vars: vpc-setup


    - name: Create a security group for bastion host
      amazon.aws.ec2_security_group:
        name: sg_bastion
        description: Security group with rule descriptions
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 22
      register: sg_bastion