---
- name: Create AWS VPC, Subnets, and Internet Gateway
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Include VPC variables
      include_vars: vpc-setup

    - name: Create a VPC
      amazon.aws.ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpcCidr }}"
        region: "{{ region }}"
        state: present
      register: vpc

    - name: Store the VPC ID
      set_fact:
        vpc_id: "{{ vpc.vpc.id }}"

    - name: Print VPC ID
      debug:
        msg: "The VPC ID is {{ vpc_id }}"

    - name: Create the first public subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_id }}"
        cidr: "{{ PubSub1Cidr }}"
        region: "{{ region }}"
        map_public: yes
        state: present
        tags:
          Name: "pubsub1"
          Environment: "Production"
      register: public_subnet1

    - name: Create the second public subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_id }}"
        cidr: "{{ PubSub2Cidr }}"
        region: "{{ region }}"
        map_public: yes
        state: present
        tags:
          Name: "pubsub2"
          Environment: "Production"
      register: public_subnet2

    - name: Create the third public subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_id }}"
        cidr: "{{ PubSub3Cidr }}"
        region: "{{ region }}"
        map_public: yes
        state: present
        tags:
          Name: "pubsub3"
          Environment: "Production"
      register: public_subnet3

    - name: Create the first private subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_id }}"
        cidr: "{{ PrivSub1Cidr }}"
        region: "{{ region }}"
        state: present
        tags:
          Name: "prvsub1"
          Environment: "Production"
      register: private_subnet1

    - name: Create the second private subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_id }}"
        cidr: "{{ PrivSub2Cidr }}"
        region: "{{ region }}"
        state: present
        tags:
          Name: "prvsub2"
          Environment: "Production"
      register: private_subnet2

    - name: Create the third private subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_id }}"
        cidr: "{{ PrivSub3Cidr }}"
        region: "{{ region }}"
        state: present
        tags:
          Name: "prvsub3"
          Environment: "Production"
      register: private_subnet3

    - name: Create an Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        tags:
          Name: "MY_ANSIBLE_IGW"
        state: present
      register: igw

    - name: Debug Internet Gateway
      debug:
        var: igw

    - name: Setup public route table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        tags:
          Name: Public-RT
        subnets:
          - "{{ public_subnet1.subnet.id }}"
          - "{{ public_subnet2.subnet.id }}"
          - "{{ public_subnet3.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
      register: public_RT


    - name: Create new nat gateway and allocate new EIP if a nat gateway does not yet exist in the subnet.
      amazon.aws.ec2_vpc_nat_gateway:
        state: present
        subnet_id: "{{ public_subnet1.subnet.id }}"
        wait: true
        region: "{{ region }}"
        if_exist_do_not_create: true
      register: nat_gateway

    - name: Setup Private route table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        tags:
          Name: Private-RT
        subnets:
          - "{{ private_subnet1.subnet.id }}"
          - "{{ private_subnet2.subnet.id }}"
          - "{{ private_subnet3.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ nat_gateway.nat_gateway_id }}"
      register: private_RT


    - name: Print VPC and Subnet IDs
      debug:
        msg: |
          VPC ID: {{ vpc_id }}
          Public Subnet 1 ID: {{ public_subnet1.subnet.id }}
          Public Subnet 2 ID: {{ public_subnet2.subnet.id }}
          Public Subnet 3 ID: {{ public_subnet3.subnet.id }}
          Private Subnet 1 ID: {{ private_subnet1.subnet.id }}
          Private Subnet 2 ID: {{ private_subnet2.subnet.id }}
          Private Subnet 3 ID: {{ private_subnet3.subnet.id }}
          Internet Gateway ID: {{ igw.gateway_id if igw is defined else 'N/A' }}
