# create_vpc.yml
- name: Create AWS VPC
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Include VPC variables
      include_vars: vpc-setup

    - name: Create a VPC
      amazon.aws.ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpcCidr }}"
        region: "{{ region }}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: present
      register: vpc

    - name: Store the VPC ID
      set_fact:
        vpc_id: "{{ vpc.vpc.id }}"

    - name: Print VPC ID
      debug:
        msg: "The VPC ID is {{ vpc_id }}"


    - name: Create the first public subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_id }}"
        cidr: "{{ public_subnet1_cidr }}"
        region: "{{ region }}"
        az: "{{ zone1 }}"
        map_public: yes
        state: present
        tags:
          Name: "pubsub1"
          Environment: "Production"
      register: public_subnet1

    - name: Create the second public subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_id }}"
        cidr: "{{ public_subnet2_cidr }}"
        region: "{{ region }}"
        az: "{{ zone2 }}"
        map_public: yes
        state: present
        tags:
          Name: "pubsub2"
          Environment: "Production"
      register: public_subnet2

    - name: Create the third public subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_id }}"
        cidr: "{{ public_subnet3_cidr }}"
        region: "{{ region }}"
        az: "{{ zone3 }}"
        map_public: yes
        state: present
        tags:
          Name: "pubsub3"
          Environment: "Production"
      register: public_subnet3

    - name: Create the first private subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_id }}"
        cidr: "{{ private_subnet1_cidr }}"
        region: "{{ region }}"
        az: "{{ zone1 }}"
        state: present
        tags:
          Name: "prvsub1"
          Environment: "Production"
      register: private_subnet1

    - name: Create the second private subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_id }}"
        cidr: "{{ private_subnet2_cidr }}"
        region: "{{ region }}"
        az: "{{ zone2 }}"
        state: present
        tags:
          Name: "prvsub2"
          Environment: "Production"
      register: private_subnet2

    - name: Create the third private subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_id }}"
        cidr: "{{ private_subnet3_cidr }}"
        region: "{{ region }}"
        az: "{{ zone3 }}"
        state: present
        tags:
          Name: "prvsub3"
          Environment: "Production"
      register: private_subnet3

    - name: Print VPC and Subnet IDs
      debug:
        msg: |
          VPC ID: {{ vpc_id }}
          Public Subnet 1 ID: {{ public_subnet1.subnet.id }}
          Public Subnet 2 ID: {{ public_subnet2.subnet.id }}
          Public Subnet 3 ID: {{ public_subnet3.subnet.id }}
          Private Subnet 1 ID: {{ private_subnet1.subnet.id }}
          Private Subnet 2 ID: {{ private_subnet2.subnet.id }}
          Private Subnet 3 ID: {{ private_subnet3.subnet.id }}    
