- name: Create EC2 for App stack
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Include out vars
      include_vars: out_IDs

    - name: Include out vars
      include_vars: vpc-setup
    
    - name: Include out vars
      include_vars: vprofile-stack-vars

    - name: Create key for ec2 instances
      amazon.aws.ec2_key:
        name: vprofilestack-key
        region: "{{ region }}"
      register: key_out

    - name: Save private key into file vprofilestack-key.pem
      copy:
        content: "{{ key_out.key.private_key }}"
        dest: "./vprofilestack-key.pem"
        mode: 0600
      when: key_out.changed

    - name: Create Security Group for Load Balancer
      amazon.aws.ec2_security_group:
        name: vproELB-sg
        description: Allow port 80 from everywhere and all ports within sg
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: vproELBSG_out

    - name: Create Security Group for Vprofile Stack
      amazon.aws.ec2_security_group:
        name: vproStack-sg
        description: Allow port 22 from everywhere and all ports within sg
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{ vproELBSG_out.group_id }}"
          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: sg-0d7fd479182d106b7
      register: vproStackSG_out

    - name: Creating Nginx web01
      amazon.aws.ec2_instance:
        key_name: vprofilestack-key
        region: "{{ region }}"
        instance_type: t2.micro
        image_id: "{{ nginx_ami }}"
        wait: yes
        wait_timeout: 300
        tags:
          Name: "web01"
          Project: Vprofile
          Owner: DevOps Team
        exact_count: 1
        vpc_subnet_id: "{{ privatesubnet1 }}"
      register: web01_out

    - name: Creating Tomcat app01
      amazon.aws.ec2_instance:
        key_name: vprofilestack-key
        region: "{{ region }}"
        instance_type: t2.micro
        image_id: "{{ tomcat_ami }}"
        wait: yes
        wait_timeout: 300
        tags:
          Name: "app01"
          Project: Vprofile
          Owner: DevOps Team
        exact_count: 1
        vpc_subnet_id: "{{ privatesubnet1 }}"
      register: app01_out

    - name: Creating Memcache mc01
      amazon.aws.ec2_instance:
        key_name: vprofilestack-key
        region: "{{ region }}"
        instance_type: t2.micro
        image_id: "{{ memcache_ami }}"
        wait: yes
        wait_timeout: 300
        tags:
          Name: "mc01"
          Project: Vprofile
          Owner: DevOps Team
        exact_count: 1
        vpc_subnet_id: "{{ privatesubnet1 }}"
      register: mc01_out

    - name: Creating RabbitMQ rmq01
      amazon.aws.ec2_instance:
        key_name: vprofilestack-key
        region: "{{ region }}"
        instance_type: t2.micro
        image_id: "{{ rmq_ami }}"
        wait: yes
        wait_timeout: 300
        tags:
          Name: "rmq01"
          Project: Vprofile
          Owner: DevOps Team
        exact_count: 1
        vpc_subnet_id: "{{ privatesubnet1 }}"
      register: rmq01_out

    - name: Creating MySQL db01
      amazon.aws.ec2_instance:
        key_name: vprofilestack-key
        region: "{{ region }}"
        instance_type: t2.micro
        image_id: "{{ mysql_ami }}"
        wait: yes
        wait_timeout: 300
        tags:
          Name: "db01"
          Project: Vprofile
          Owner: DevOps Team
        exact_count: 1
        vpc_subnet_id: "{{ privatesubnet1 }}"
      register: db01_out

    - name: Print the instance ID
      debug:
        msg: "Instance ID: {{ db01_out.instance_ids[0] }}"

  

    - amazon.aws.elb_application_lb:
       name: myalb
       region: "{{ region }}"
       security_groups:
        - "{{ vproELBSG_out.group_id }}"
        
       subnets:
        -  subnet-0500aa02ae788a103
        -  subnet-01f96aa119729bce9
       listeners:
        - Protocol: HTTP # Required. The protocol for connections from clients to the load balancer (HTTP or HTTPS) (case-sensitive).
          Port: 80 # Required. The port on which the load balancer is listening.
          DefaultActions:
            - Type: forward  
              TargetGroupName: mytarget


    - name: Create a variable to IPs
      set_fact:
       ips_info: |
         web01_ip: "{{ web01_out.instances[0].private_ip_address }}"
         app01_ip: "{{ app01_out.instances[0].private_ip_address }}"
         rmq01_ip: "{{ rmq01_out.instances[0].private_ip_address }}"
         mc01_ip: "{{ mc01_out.instances[0].private_ip_address }}"
         db01_ip: "{{ db01_out.instances[0].private_ip_address }}"

    - name: Write IPs to a file
      copy:
        content: "{{ ips_info }}"
        dest: /provision-stack/group_vras/hostsip


   
