- name: Create bastion host
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Include out vars
    include_vars: out_IDs

  - name: Include out vars
    include_vars: vpc-setup

  - name: Create key for ec2 instances
    amazon.aws.ec2_key:
      name: vprofilestack-key
      region: "{{region}}"
    register: key_out

  - name: Save private key into file vprofilestack-key.pem

    copy:
      content: "{{key_out.key.private_key}}"
      dest: "./vprofilestack-key.pem"
      mode: 0600
    when: key_out.changed
